// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_, "1111");
    lv_obj_set_width(ui_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_, 11);
    lv_obj_set_y(ui_, -18);
    lv_obj_set_align(ui_, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


}
